services:
  postgres:
    image: postgres:15
    container_name: job_postgres
    restart: always
    environment:
      POSTGRES_DB: jobdb
      POSTGRES_USER: pg1
      POSTGRES_PASSWORD: pg1
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local