services:
  postgres:
    image: postgres:15
    container_name: job_postgres
    restart: always
    environment:
      POSTGRES_DB: jobdb
      POSTGRES_USER: jobdb
      POSTGRES_PASSWORD: jobdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local